-- Remove only local performance data generated by performance scripts.

DELETE ri
FROM recommendation_item ri
JOIN score_snapshot ss ON ss.id = ri.snapshot_id
WHERE ss.request_id LIKE 'perf-%'
   OR ss.source LIKE 'perf_%';
DELETE FROM import_task
WHERE request_id LIKE 'perf-%';

DELETE sr
FROM score_record sr
JOIN score_snapshot ss ON ss.id = sr.snapshot_id
WHERE ss.request_id LIKE 'perf-%'
   OR ss.source LIKE 'perf_%';

DELETE FROM score_snapshot
WHERE request_id LIKE 'perf-%'
   OR source LIKE 'perf_%';

DELETE FROM `user`
WHERE id IN (990001, 990002)
  AND openid LIKE 'perf-openid-%';

SELECT COUNT(*) AS remaining_perf_snapshots
FROM score_snapshot
WHERE request_id LIKE 'perf-%'
   OR source LIKE 'perf_%';

SELECT COUNT(*) AS remaining_perf_records
FROM score_record sr
JOIN score_snapshot ss ON ss.id = sr.snapshot_id
WHERE ss.request_id LIKE 'perf-%'
   OR ss.source LIKE 'perf_%';
